services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: buscaradvogado-postgres
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=buscaradvogado
    ports:
      - 5432:5432
    volumes:
      - ~/.docker/data/postgres:/var/lib/postgresql/data
  
  redis:
    image: bitnami/redis:latest
    container_name: buscaradvogado-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ~/.docker/data/redis:/data

  s3:
    image: bitnami/minio:latest
    container_name: buscaradvogado-s3
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio-pass
      - MINIO_SCHEME=http
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/.docker/data/s3:/data
