services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: buscaradvogado-postgres
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=buscaradvogado
    ports:
      - 5432:5432
    volumes:
      - ~/.docker/data/postgres:/var/lib/postgresql/data
      